// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using Exam_system_App.Entities;

namespace Exam_system_App.Context
{
    public partial class DBContext
    {

        [DbFunction("TF_Q", "dbo")]
        public static int? TF_Q(int? EX_ID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
